# Generated by Django 5.2.7 on 2026-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('valor', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'db_table': 'Parametros',
                'managed': True,
            },
        ),
    ]
