# Generated by Django 5.2.7 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', null=True)),
                ('valor', models.CharField(blank=True, db_column='Valor', null=True)),
            ],
            options={
                'db_table': 'Parametros',
                'managed': True,
            },
        ),
    ]
