# Generated by Django 5.2.7 on 2026-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'managed': True, 'permissions': [('export_pdf_parametro', 'Puede exportar Parámetros a PDF'), ('export_excel_parametro', 'Puede exportar Parámetros a Excel')], 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
    ]
