# Generated by Django 5.2.7 on 2026-01-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField()),
                ('mensaje', models.CharField(db_column='Mensaje')),
                ('tipo', models.CharField(db_column='Tipo')),
                ('leida', models.BooleanField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'Notificaciones',
                'managed': True,
            },
        ),
    ]
