# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacione',
            options={'managed': True, 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
