# Generated by Django 5.2.7 on 2026-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0002_alter_notificacione_creado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacione',
            options={'managed': True, 'permissions': [('export_pdf_notificacione', 'Puede exportar Notificaciones a PDF'), ('export_excel_notificacione', 'Puede exportar Notificaciones a Excel')], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
