# Generated by Django 5.2.7 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallesOrdene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.FloatField(db_column='Precio_Unitario')),
                ('cantidad', models.BigIntegerField(db_column='Cantidad')),
                ('subtotal', models.FloatField(db_column='subtotal')),
            ],
            options={
                'db_table': 'Detalles_Orden',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPagos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'Estado_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo')),
                ('descripcion', models.CharField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'Metodos_Pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenesVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_factura', models.CharField(blank=True, db_column='ID_Factura', null=True)),
                ('rtn', models.BooleanField(db_column='RTN')),
                ('descuento', models.FloatField(blank=True, db_column='Descuento', null=True)),
                ('subtotal', models.FloatField(db_column='SubTotal')),
                ('isv', models.FloatField(db_column='ISV')),
                ('total', models.FloatField(db_column='Total')),
                ('cuotas', models.BooleanField()),
                ('pagado', models.FloatField(blank=True, null=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True, db_column='Fecha_Orden')),
                ('fecha_entrega', models.DateField(db_column='Fecha_Entrega')),
                ('efectivo', models.FloatField(blank=True, null=True)),
                ('num_tarjeta', models.CharField(blank=True, max_length=4, null=True, verbose_name='Numero de Tarjeta')),
            ],
            options={
                'db_table': 'Ordenes_Ventas',
                'managed': True,
            },
        ),
    ]
