# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compras', '0001_initial'),
        ('Empleados', '0001_initial'),
        ('Muebles', '0001_initial'),
        ('Sucursales', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPagos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado de Pago',
                'verbose_name_plural': 'Estados de Pago',
                'db_table': 'Estado_Pagos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'Metodos_Pago',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenesVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_factura', models.CharField(blank=True, null=True)),
                ('rtn', models.BooleanField()),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('subtotal', models.FloatField()),
                ('isv', models.FloatField()),
                ('total', models.FloatField()),
                ('cuotas', models.BooleanField()),
                ('pagado', models.FloatField(blank=True, null=True)),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('efectivo', models.FloatField(blank=True, null=True)),
                ('num_tarjeta', models.CharField(blank=True, max_length=4, null=True, verbose_name='Numero de Tarjeta')),
                ('cai_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.cai')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente', verbose_name='Cliente')),
                ('id_cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.cotizacione', verbose_name='Cotizacion')),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Empleados.perfilusuario', verbose_name='Empleado')),
                ('id_estado_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.estadopagos', verbose_name='Estado del pago')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.metodospago', verbose_name='Metodo de pago')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Ventas',
                'db_table': 'Ordenes_Ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallesOrdene',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.FloatField(verbose_name='Precio Unitario')),
                ('cantidad', models.BigIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.FloatField(verbose_name='Subtotal')),
                ('id_mueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble', verbose_name='Mueble')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ventas.ordenesventa', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Ordenes',
                'db_table': 'Detalles_Orden',
                'managed': True,
            },
        ),
    ]
