# Generated by Django 5.2.7 on 2026-03-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesordene',
            options={'managed': True, 'permissions': [('export_pdf_DetallesOrden', 'Puede exportar Detalles de Orden a PDF'), ('export_excel_DetallesOrden', 'Puede exportar Detalles de Orden a Excel')], 'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='estadopagos',
            options={'managed': True, 'permissions': [('export_pdf_EstadoPagos', 'Puede exportar Estados de Pago a PDF'), ('export_excel_EstadoPagos', 'Puede exportar Estados de Pago a Excel')], 'verbose_name': 'Estado de Pago', 'verbose_name_plural': 'Estados de Pago'},
        ),
        migrations.AlterModelOptions(
            name='metodospago',
            options={'managed': True, 'permissions': [('export_pdf_MetodosPago', 'Puede exportar Métodos de Pago a PDF'), ('export_excel_MetodosPago', 'Puede exportar Métodos de Pago a Excel')], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='ordenesventa',
            options={'managed': True, 'permissions': [('export_pdf_ordenesventa', 'Puede exportar Órdenes de Venta a PDF'), ('export_excel_ordenesventa', 'Puede exportar Órdenes de Venta a Excel')], 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Ordenes de Ventas'},
        ),
    ]
