# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesordene',
            options={'managed': False, 'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='estadopagos',
            options={'managed': False, 'verbose_name': 'Estado de Pago', 'verbose_name_plural': 'Estados de Pago'},
        ),
        migrations.AlterModelOptions(
            name='metodospago',
            options={'managed': False, 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.AlterModelOptions(
            name='ordenesventa',
            options={'managed': False, 'verbose_name': 'Orden de Venta', 'verbose_name_plural': 'Ordenes de Ventas'},
        ),
    ]
