# Generated by Django 5.2.7 on 2026-03-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_detallesordene_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallesordene',
            options={'managed': True, 'permissions': [('export_pdf_detallesordene', 'Puede exportar Detalles de Orden a PDF'), ('export_excel_detallesordene', 'Puede exportar Detalles de Orden a Excel')], 'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Ordenes'},
        ),
    ]
