# Generated by Django 5.2.7 on 2026-03-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_alter_detallesordene_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadopagos',
            options={'managed': True, 'permissions': [('export_pdf_estadopagos', 'Puede exportar Estados de Pago a PDF'), ('export_excel_estadopagos', 'Puede exportar Estados de Pago a Excel')], 'verbose_name': 'Estado de Pago', 'verbose_name_plural': 'Estados de Pago'},
        ),
        migrations.AlterModelOptions(
            name='metodospago',
            options={'managed': True, 'permissions': [('export_pdf_metodospago', 'Puede exportar Métodos de Pago a PDF'), ('export_excel_metodospago', 'Puede exportar Métodos de Pago a Excel')], 'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
    ]
