# Generated by Django 5.2.7 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AportacionEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant_aprobada', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_finalizada', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando'), ('completo', 'Completo')], default='pendiente')),
                ('materiales_reservados', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'aportacion_empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenMensualDetalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_planificada', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_producida', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('incompleto', 'Incompleto'), ('completo', 'Completo')], default=1)),
                ('entrega_estim', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Orden_mensual_detalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenMensuale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion')),
                ('observaciones', models.CharField(blank=True, null=True)),
                ('fecha_fin', models.DateField(db_column='Fecha_fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('incompleto', 'Incompleto'), ('completo', 'Completo')], default='pendiente', null=True)),
            ],
            options={
                'db_table': 'Orden_Mensuales',
                'managed': True,
            },
        ),
    ]
