# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Muebles', '0001_initial'),
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMensualDetalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_planificada', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_producida', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('incompleto', 'Incompleto'), ('completo', 'Completo')], default=1)),
                ('entrega_estim', models.DateField(blank=True, null=True)),
                ('id_mueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble')),
            ],
            options={
                'verbose_name': 'Detalle de Orden Mensual',
                'verbose_name_plural': 'Detalles de Ordenes Mensuales',
                'db_table': 'Orden_mensual_detalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AportacionEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cant_aprobada', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_finalizada', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('trabajando', 'Trabajando'), ('completo', 'Completo')], default='pendiente')),
                ('materiales_reservados', models.JSONField(blank=True, default=dict)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Empleados.perfilusuario')),
                ('id_orden_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Trabajo.ordenmensualdetalle')),
            ],
            options={
                'verbose_name': 'Aportación de Empleado',
                'verbose_name_plural': 'Aportaciones de Empleados',
                'db_table': 'aportacion_empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdenMensuale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, null=True)),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('incompleto', 'Incompleto'), ('completo', 'Completo')], default='pendiente', null=True)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'Orden Mensual',
                'verbose_name_plural': 'Ordenes Mensuales',
                'db_table': 'Orden_Mensuales',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ordenmensualdetalle',
            name='id_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Trabajo.ordenmensuale'),
        ),
    ]
