# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportacionempleado',
            options={'managed': False, 'verbose_name': 'Aportación de Empleado', 'verbose_name_plural': 'Aportaciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='ordenmensualdetalle',
            options={'managed': False, 'verbose_name': 'Detalle de Orden Mensual', 'verbose_name_plural': 'Detalles de Ordenes Mensuales'},
        ),
        migrations.AlterModelOptions(
            name='ordenmensuale',
            options={'managed': False, 'verbose_name': 'Orden Mensual', 'verbose_name_plural': 'Ordenes Mensuales'},
        ),
    ]
