# Generated by Django 5.2.7 on 2026-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aportacionempleado',
            options={'managed': True, 'permissions': [('export_pdf_aportacionempleado', 'Puede exportar Aportaciones de Empleados a PDF'), ('export_excel_aportacionempleado', 'Puede exportar Aportaciones de Empleados a Excel')], 'verbose_name': 'Aportación de Empleado', 'verbose_name_plural': 'Aportaciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='ordenmensualdetalle',
            options={'managed': True, 'permissions': [('export_pdf_ordenmensualdetalle', 'Puede exportar Detalles de Ordenes Mensuales a PDF'), ('export_excel_ordenmensualdetalle', 'Puede exportar Detalles de Ordenes Mensuales a Excel')], 'verbose_name': 'Detalle de Orden Mensual', 'verbose_name_plural': 'Detalles de Ordenes Mensuales'},
        ),
        migrations.AlterModelOptions(
            name='ordenmensuale',
            options={'managed': True, 'permissions': [('export_pdf_ordenmensuale', 'Puede exportar Ordenes Mensuales a PDF'), ('export_excel_ordenmensuale', 'Puede exportar Ordenes Mensuales a Excel')], 'verbose_name': 'Orden Mensual', 'verbose_name_plural': 'Ordenes Mensuales'},
        ),
    ]
