# Generated by Django 5.2.7 on 2026-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criterio', models.CharField(choices=[('puntualidad', 'Puntualidad'), ('calidad material', 'Calidad Material'), ('comunicacion', 'Comunicación'), ('Precio', 'Precio')], db_column='Criterio', default=1)),
                ('calificacion', models.BigIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_column='Calificacion', default=1)),
                ('comentario', models.CharField(db_column='Comentario')),
            ],
            options={
                'db_table': 'Calificaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriasMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion')),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Categorias_Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadosPersonas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', null=True)),
            ],
            options={
                'db_table': 'Estados_personas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(db_column='Precio')),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(db_column='Fecha_Fin')),
            ],
            options={
                'db_table': 'Historial_Precios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('imagen', models.TextField()),
                ('stock_minimo', models.BigIntegerField(db_column='Stock_Minimo')),
                ('stock_maximo', models.BigIntegerField(db_column='Stock_Maximo')),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialProveedore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('precio_actual', models.FloatField(db_column='precio')),
                ('tiempo', models.BigIntegerField(db_column='Tiempo')),
                ('unidad_tiempo', models.CharField(choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], db_column='Unidad tiempo', default='dias', max_length=10)),
                ('comentarios', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'Material_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compañia', models.CharField(db_column='Compañia', help_text='Aquí se ingresará el nombre de la compañía proveedora.')),
                ('nombre', models.CharField(db_column='Nombre')),
                ('telefono', models.CharField(db_column='Telefono')),
                ('email', models.CharField(db_column='email', max_length=50)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=15)),
                ('abreviatura', models.CharField(db_column='Abreviatura', max_length=4)),
            ],
            options={
                'db_table': 'Unidades_Medida',
                'managed': True,
            },
        ),
    ]
