# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
                'db_table': 'Categorias_Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadosPersonas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Persona',
                'verbose_name_plural': 'Estados de Personas',
                'db_table': 'Estados_personas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('abreviatura', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'Unidades_Medida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('imagen', models.TextField()),
                ('stock_minimo', models.BigIntegerField()),
                ('stock_maximo', models.BigIntegerField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.categoriasmateriale')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.unidadesmedida')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('compañia', models.CharField(help_text='Aquí se ingresará el nombre de la compañía proveedora.', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.estadospersonas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MaterialProveedore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('precio_actual', models.FloatField()),
                ('tiempo', models.BigIntegerField()),
                ('unidad_tiempo', models.CharField(choices=[('dias', 'Días'), ('semanas', 'Semanas'), ('meses', 'Meses')], default='dias', max_length=10)),
                ('comentarios', models.TextField(blank=True, max_length=150, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.proveedore')),
            ],
            options={
                'verbose_name': 'Material Proveedor',
                'verbose_name_plural': 'Materiales Proveedores',
                'db_table': 'Material_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.proveedore')),
            ],
            options={
                'verbose_name': 'Historial de Precio',
                'verbose_name_plural': 'Historiales de Precios',
                'db_table': 'Historial_Precios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Calificacione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('criterio', models.CharField(choices=[('puntualidad', 'Puntualidad'), ('calidad material', 'Calidad Material'), ('comunicacion', 'Comunicación'), ('Precio', 'Precio')], default=1)),
                ('calificacion', models.BigIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('comentario', models.CharField(max_length=255)),
                ('id_prov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.proveedore', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Calificaciones',
                'managed': True,
            },
        ),
    ]
