# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacione',
            options={'managed': False, 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='categoriasmateriale',
            options={'managed': False, 'verbose_name': 'Categoría de Material', 'verbose_name_plural': 'Categorías de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='estadospersonas',
            options={'managed': False, 'verbose_name': 'Estado de Persona', 'verbose_name_plural': 'Estados de Personas'},
        ),
        migrations.AlterModelOptions(
            name='historialprecio',
            options={'managed': False, 'verbose_name': 'Historial de Precio', 'verbose_name_plural': 'Historiales de Precios'},
        ),
        migrations.AlterModelOptions(
            name='materiale',
            options={'managed': False, 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='materialproveedore',
            options={'managed': False, 'verbose_name': 'Material Proveedor', 'verbose_name_plural': 'Materiales Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedore',
            options={'managed': False, 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='unidadesmedida',
            options={'managed': False, 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
