# Generated by Django 5.2.7 on 2026-02-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
