# Generated by Django 5.2.7 on 2025-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion')),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Categorias_Materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('imagen', models.TextField()),
                ('stock_minimo', models.BigIntegerField(db_column='Stock_Minimo')),
                ('stock_maximo', models.BigIntegerField(db_column='Stock_Maximo')),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Materiales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('abreviatura', models.CharField(db_column='Abreviatura', max_length=10)),
            ],
            options={
                'db_table': 'Unidades_Medida',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CategoriasMateriales',
        ),
    ]
