# Generated by Django 5.2.7 on 2026-03-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0002_alter_historialprecio_fecha_fin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacione',
            options={'managed': True, 'permissions': [('export_pdf_calificacione', 'Puede exportar Calificaciones a PDF'), ('export_excel_calificacione', 'Puede exportar Calificaciones a Excel')], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.AlterModelOptions(
            name='categoriasmateriale',
            options={'managed': True, 'permissions': [('export_pdf_categoriasmateriale', 'Puede exportar Categorías de Materiales a PDF'), ('export_excel_categoriasmateriale', 'Puede exportar Categorías de Materiales a Excel')], 'verbose_name': 'Categoría de Material', 'verbose_name_plural': 'Categorías de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='estadospersonas',
            options={'managed': True, 'permissions': [('export_pdf_estadospersonas', 'Puede exportar Estados de Personas a PDF'), ('export_excel_estadospersonas', 'Puede exportar Estados de Personas a Excel')], 'verbose_name': 'Estado de Persona', 'verbose_name_plural': 'Estados de Personas'},
        ),
        migrations.AlterModelOptions(
            name='historialprecio',
            options={'managed': True, 'permissions': [('export_pdf_historialprecio', 'Puede exportar Historiales de Precios a PDF'), ('export_excel_historialprecio', 'Puede exportar Historiales de Precios a Excel')], 'verbose_name': 'Historial de Precio', 'verbose_name_plural': 'Historiales de Precios'},
        ),
        migrations.AlterModelOptions(
            name='materiale',
            options={'managed': True, 'permissions': [('export_pdf_materiale', 'Puede exportar Materiales a PDF'), ('export_excel_materiale', 'Puede exportar Materiales a Excel')], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='materialproveedore',
            options={'managed': True, 'permissions': [('export_pdf_materialproveedore', 'Puede exportar Materiales Proveedores a PDF'), ('export_excel_materialproveedore', 'Puede exportar Materiales Proveedores a Excel')], 'verbose_name': 'Material Proveedor', 'verbose_name_plural': 'Materiales Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='proveedore',
            options={'managed': True, 'permissions': [('export_pdf_proveedore', 'Puede exportar Proveedores a PDF'), ('export_excel_proveedore', 'Puede exportar Proveedores a Excel')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='unidadesmedida',
            options={'managed': True, 'permissions': [('export_pdf_unidadesmedida', 'Puede exportar Unidades de Medida a PDF'), ('export_excel_unidadesmedida', 'Puede exportar Unidades de Medida a Excel')], 'verbose_name': 'Unidad de Medida', 'verbose_name_plural': 'Unidades de Medida'},
        ),
    ]
