# Generated by Django 5.2.7 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_cai', models.CharField(db_column='Codigo_Cai', max_length=37)),
                ('fecha_emision', models.DateField(db_column='Fecha_Emision')),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
                ('rango_inicial', models.CharField(db_column='Rango_Inicial')),
                ('rango_final', models.CharField(db_column='Rango_Final')),
                ('ultima_secuencia', models.CharField(db_column='Ultima_Secuencia')),
                ('activo', models.BooleanField(db_column='Activo')),
            ],
            options={
                'db_table': 'CAI',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_caja', models.CharField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_sucursal', models.CharField(db_column='codigo_sucursal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('direccion', models.CharField(db_column='Direccion')),
                ('telefono', models.CharField(db_column='Telefono')),
                ('rtn', models.CharField(blank=True, db_column='RTN', null=True)),
            ],
            options={
                'db_table': 'Sucursales',
                'managed': True,
            },
        ),
    ]
