# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_sucursal', models.CharField(max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('rtn', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_caja', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'caja',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cai',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo_cai', models.CharField(max_length=37)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('rango_inicial', models.CharField(max_length=8)),
                ('rango_final', models.CharField(max_length=8)),
                ('ultima_secuencia', models.CharField(max_length=8)),
                ('activo', models.BooleanField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale')),
            ],
            options={
                'verbose_name': 'CAI',
                'verbose_name_plural': 'CAIs',
                'db_table': 'CAI',
                'managed': True,
            },
        ),
    ]
