# Generated by Django 5.2.7 on 2026-03-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cai',
            options={'managed': True, 'permissions': [('export_pdf_cai', 'Puede exportar CAIs a PDF'), ('export_excel_cai', 'Puede exportar CAIs a Excel')], 'verbose_name': 'CAI', 'verbose_name_plural': 'CAIs'},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'managed': True, 'permissions': [('export_pdf_caja', 'Puede exportar Cajas a PDF'), ('export_excel_caja', 'Puede exportar Cajas a Excel')], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='sucursale',
            options={'managed': True, 'permissions': [('export_pdf_sucursale', 'Puede exportar Sucursales a PDF'), ('export_excel_sucursale', 'Puede exportar Sucursales a Excel')], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
