# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cai',
            options={'managed': False, 'verbose_name': 'CAI', 'verbose_name_plural': 'CAIs'},
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'managed': False, 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='sucursale',
            options={'managed': False, 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
