# Generated by Django 5.2.7 on 2026-03-10 06:18

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'permissions': [('export_pdf_groupproxy', 'Puede exportar Grupos a PDF'), ('export_excel_groupproxy', 'Puede exportar Grupos a Excel')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': [('export_pdf_userproxy', 'Puede exportar Usuarios a PDF'), ('export_excel_userproxy', 'Puede exportar Usuarios a Excel')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True, 'permissions': [('export_pdf_empleado', 'Puede exportar Empleados a PDF'), ('export_excel_empleado', 'Puede exportar Empleados a Excel')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'managed': True, 'permissions': [('export_pdf_perfilusuario', 'Puede exportar Perfiles de Usuario a PDF'), ('export_excel_perfilusuario', 'Puede exportar Perfiles de Usuario a Excel')], 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'permissions': [('export_pdf_user', 'Puede exportar Usuarios a PDF'), ('export_excel_user', 'Puede exportar Usuarios a Excel')]},
        ),
    ]
