# Generated by Django 5.2.7 on 2025-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMateriales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion')),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
                ('archivo_temp', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Categorias_Materiales',
                'managed': False,
            },
        ),
    ]
