# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Mueble',
                'verbose_name_plural': 'Categorías de Muebles',
                'db_table': 'Categorias_Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'db_table': 'Tamano',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=250)),
                ('precio_base', models.FloatField()),
                ('alto', models.FloatField()),
                ('ancho', models.FloatField()),
                ('largo', models.FloatField()),
                ('imagen', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, null=True)),
                ('Descontinuado', models.BooleanField()),
                ('stock_minimo', models.BigIntegerField()),
                ('stock_maximo', models.BigIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.categoriasmueble')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.unidadesmedida')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.tamaño')),
            ],
            options={
                'verbose_name': 'Mueble',
                'verbose_name_plural': 'Muebles',
                'db_table': 'Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialPreciosMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_mueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble')),
            ],
            options={
                'verbose_name': 'Historial de Precio de Mueble',
                'verbose_name_plural': 'Historiales de Precios de Muebles',
                'db_table': 'Historial_Precios_muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MuebleMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('id_mueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble')),
            ],
            options={
                'verbose_name': 'Mueble Material',
                'verbose_name_plural': 'Muebles Materiales',
                'db_table': 'Mueble_Material',
                'managed': True,
            },
        ),
    ]
