# Generated by Django 5.2.7 on 2026-01-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.CharField(db_column='Descripcion')),
                ('imagen', models.TextField()),
                ('imagen_url', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Categorias_Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialPreciosMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(db_column='Precio')),
                ('fecha_inicio', models.DateField(db_column='Fecha_Inicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='Fecha_Fin', null=True)),
            ],
            options={
                'db_table': 'Historial_Precios_muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('descripcion', models.TextField(db_column='Descripcion', max_length=250)),
                ('precio_base', models.FloatField(db_column='Precio_Base')),
                ('alto', models.FloatField(db_column='Alto')),
                ('ancho', models.FloatField(db_column='Ancho')),
                ('largo', models.FloatField(db_column='Largo')),
                ('imagen', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, null=True)),
                ('Descontinuado', models.BooleanField(db_column='Estado')),
                ('stock_minimo', models.BigIntegerField(db_column='Stock_Minimo')),
                ('stock_maximo', models.BigIntegerField(db_column='Stock_Maximo')),
            ],
            options={
                'db_table': 'Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MuebleMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'Mueble_Material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Tamano',
                'managed': True,
            },
        ),
    ]
