# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasmueble',
            options={'managed': False, 'verbose_name': 'Categoría de Mueble', 'verbose_name_plural': 'Categorías de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='historialpreciosmueble',
            options={'managed': False, 'verbose_name': 'Historial de Precio de Mueble', 'verbose_name_plural': 'Historiales de Precios de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='mueble',
            options={'managed': False, 'verbose_name': 'Mueble', 'verbose_name_plural': 'Muebles'},
        ),
        migrations.AlterModelOptions(
            name='mueblemateriale',
            options={'managed': False, 'verbose_name': 'Mueble Material', 'verbose_name_plural': 'Muebles Materiales'},
        ),
        migrations.AlterModelOptions(
            name='tamaño',
            options={'managed': False, 'verbose_name': 'Tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
    ]
