# Generated by Django 5.2.7 on 2026-03-10 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Muebles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasmueble',
            options={'managed': True, 'permissions': [('export_pdf_categoriasmueble', 'Puede exportar Categorías de Muebles a PDF'), ('export_excel_categoriasmueble', 'Puede exportar Categorías de Muebles a Excel')], 'verbose_name': 'Categoría de Mueble', 'verbose_name_plural': 'Categorías de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='historialpreciosmueble',
            options={'managed': True, 'permissions': [('export_pdf_historialpreciosmueble', 'Puede exportar Historiales de Precios de Muebles a PDF'), ('export_excel_historialpreciosmueble', 'Puede exportar Historiales de Precios de Muebles a Excel')], 'verbose_name': 'Historial de Precio de Mueble', 'verbose_name_plural': 'Historiales de Precios de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='mueble',
            options={'managed': True, 'permissions': [('export_pdf_mueble', 'Puede exportar Muebles a PDF'), ('export_excel_mueble', 'Puede exportar Muebles a Excel')], 'verbose_name': 'Mueble', 'verbose_name_plural': 'Muebles'},
        ),
        migrations.AlterModelOptions(
            name='mueblemateriale',
            options={'managed': True, 'permissions': [('export_pdf_mueblemateriale', 'Puede exportar Muebles Materiales a PDF'), ('export_excel_mueblemateriale', 'Puede exportar Muebles Materiales a Excel')], 'verbose_name': 'Mueble Material', 'verbose_name_plural': 'Muebles Materiales'},
        ),
        migrations.AlterModelOptions(
            name='tamaño',
            options={'managed': True, 'permissions': [('export_pdf_tamaño', 'Puede exportar Tamaños a PDF'), ('export_excel_tamaño', 'Puede exportar Tamaños a Excel')], 'verbose_name': 'Tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
    ]
