# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('rtn', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('id_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='archivos.documento')),
            ],
            options={
                'verbose_name': 'Documento del Cliente',
                'verbose_name_plural': 'Documentos de los Clientes',
                'db_table': 'Documentos_Clientes',
                'managed': True,
            },
        ),
    ]
