# Generated by Django 5.2.7 on 2026-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(db_column='Nombre')),
                ('telefono', models.CharField(db_column='Telefono')),
                ('direccion', models.CharField(db_column='Direccion')),
                ('rtn', models.CharField(blank=True, db_column='RTN', max_length=16, null=True)),
            ],
            options={
                'db_table': 'Clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocumentosCliente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(db_column='Valor')),
            ],
            options={
                'db_table': 'Documentos_Clientes',
                'managed': True,
            },
        ),
    ]
