# Generated by Django 5.2.7 on 2026-03-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoscliente',
            options={'managed': True, 'permissions': [('export_pdf_documentoscliente', 'Puede exportar Documentos de Cliente a PDF'), ('export_excel_documentoscliente', 'Puede exportar Documentos de Cliente a Excel')], 'verbose_name': 'Documento del Cliente', 'verbose_name_plural': 'Documentos de los Clientes'},
        ),
    ]
