# Generated by Django 5.2.7 on 2026-03-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_documentoscliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True, 'permissions': [('export_pdf_cliente', 'Puede exportar Cliente a PDF'), ('export_excel_cliente', 'Puede exportar Cliente a Excel')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
