# Generated by Django 5.2.7 on 2026-01-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(db_column='Estado', default=True)),
                ('fecha_vencimiento', models.DateField(db_column='Fecha_Vencimiento')),
                ('subtotal', models.FloatField(blank=True, db_column='SubTotal', null=True)),
                ('isv', models.FloatField(blank=True, db_column='ISV', null=True)),
                ('total', models.FloatField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'db_table': 'Cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(db_column='Cantidad')),
                ('precio_unitario', models.FloatField(db_column='Precio_Unitario')),
                ('subtotal', models.FloatField(db_column='SubTotal')),
            ],
            options={
                'db_table': 'Detalle_Cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleRecibido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_ord', models.BigIntegerField(blank=True, null=True)),
                ('aporte', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_recibida', models.BigIntegerField(blank=True, null=True)),
                ('estado_item', models.CharField(blank=True, choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('excedido', 'Exedido')], null=True)),
            ],
            options={
                'db_table': 'Detalle_recibido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', null=True)),
            ],
            options={
                'db_table': 'Estados_M',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.BigIntegerField(db_column='Cantidad_Disponible')),
                ('ultima_entrada', models.DateField(blank=True, db_column='ultima entrada', null=True)),
                ('ultima_salida', models.DateField(blank=True, db_column='ultima salida', null=True)),
                ('cantidad_reservada', models.BigIntegerField(blank=True, db_column='Cantidad_Reservada', null=True)),
            ],
            options={
                'db_table': 'Inventario_Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.BigIntegerField(db_column='Cantidad_Disponible')),
                ('ultima_entrada', models.DateField(blank=True, db_column='ultima entrada', null=True)),
                ('ultima_salida', models.DateField(blank=True, db_column='ultima salida', null=True)),
            ],
            options={
                'db_table': 'Inventario_Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, db_column='Fecha_Solicitud')),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='Fecha_Entrega', null=True, verbose_name='Fecha Entrega Completa')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_column='Prioridad', default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('incompleta', 'Incompleta'), ('completa', 'Completa'), ('recibida', 'Recibida')], db_column='Estado', default=3)),
            ],
            options={
                'db_table': 'Lista_Compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', null=True)),
                ('valor', models.CharField(blank=True, db_column='Valor', null=True)),
            ],
            options={
                'db_table': 'Parametros',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.BigIntegerField(db_column='Cantidad_Necesaria')),
                ('motivo', models.CharField(choices=[('reposicion stock', 'Reposición stock'), ('stock insuficiente', 'Stock insuficiente'), ('sin stock', 'Sin Stock')], db_column='Motivo', default=1)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], db_column='Prioridad', default=3)),
                ('precio_actual', models.FloatField(db_column='precio')),
                ('subtotal', models.FloatField(db_column='subtotal')),
            ],
            options={
                'db_table': 'Requerimiento_Material',
                'managed': True,
            },
        ),
    ]
