# Generated by Django 5.2.7 on 2026-02-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materiales', '0001_initial'),
        ('Muebles', '0001_initial'),
        ('Sucursales', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Mueble',
                'verbose_name_plural': 'Estados de Muebles',
                'db_table': 'Estados_M',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotizacione',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vencimiento', models.DateField()),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('isv', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'Cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.cotizacione')),
                ('id_mueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
                'db_table': 'Detalle_Cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.BigIntegerField()),
                ('ultima_entrada', models.DateField(blank=True, null=True)),
                ('ultima_salida', models.DateField(blank=True, null=True)),
                ('cantidad_reservada', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.estados')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('ubicación', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale')),
            ],
            options={
                'verbose_name': 'Inventario de Material',
                'verbose_name_plural': 'Inventarios de Materiales',
                'db_table': 'Inventario_Materiales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioMueble',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.BigIntegerField()),
                ('ultima_entrada', models.DateField(blank=True, null=True)),
                ('ultima_salida', models.DateField(blank=True, null=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.estados')),
                ('id_mueble', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Muebles.mueble')),
                ('ubicación', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale')),
            ],
            options={
                'verbose_name': 'Inventario de Mueble',
                'verbose_name_plural': 'Inventarios de Muebles',
                'db_table': 'Inventario_Muebles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Entrega Completa')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('incompleta', 'Incompleta'), ('completa', 'Completa'), ('recibida', 'Recibida')], default=3)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursale')),
            ],
            options={
                'verbose_name': 'Lista de Compra',
                'verbose_name_plural': 'Listas de Compras',
                'db_table': 'Lista_Compras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleRecibido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_ord', models.BigIntegerField(blank=True, null=True)),
                ('aporte', models.BigIntegerField(blank=True, null=True)),
                ('cantidad_recibida', models.BigIntegerField(blank=True, null=True)),
                ('estado_item', models.CharField(blank=True, choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('excedido', 'Exedido')], null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.listacompra')),
            ],
            options={
                'verbose_name': 'Detalle Recibido',
                'verbose_name_plural': 'Detalles Recibidos',
                'db_table': 'Detalle_recibido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMateriale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad_necesaria', models.BigIntegerField()),
                ('motivo', models.CharField(choices=[('reposicion stock', 'Reposición stock'), ('stock insuficiente', 'Stock insuficiente'), ('sin stock', 'Sin Stock')], default=1)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default=3)),
                ('precio_actual', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('id_lista', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Compras.listacompra')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.materiale')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Materiales.proveedore')),
            ],
            options={
                'verbose_name': 'Requerimiento de Material',
                'verbose_name_plural': 'Requerimientos de Materiales',
                'db_table': 'Requerimiento_Material',
                'managed': True,
            },
        ),
    ]
