# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacione',
            options={'managed': False, 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizaciones',
            options={'managed': False, 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallerecibido',
            options={'managed': False, 'verbose_name': 'Detalle Recibido', 'verbose_name_plural': 'Detalles Recibidos'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': False, 'verbose_name': 'Estado de Mueble', 'verbose_name_plural': 'Estados de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='inventariomateriale',
            options={'managed': False, 'verbose_name': 'Inventario de Material', 'verbose_name_plural': 'Inventarios de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='inventariomueble',
            options={'managed': False, 'verbose_name': 'Inventario de Mueble', 'verbose_name_plural': 'Inventarios de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='listacompra',
            options={'managed': False, 'verbose_name': 'Lista de Compra', 'verbose_name_plural': 'Listas de Compras'},
        ),
        migrations.AlterModelOptions(
            name='parametro',
            options={'managed': False, 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.AlterModelOptions(
            name='requerimientomateriale',
            options={'managed': False, 'verbose_name': 'Requerimiento de Material', 'verbose_name_plural': 'Requerimientos de Materiales'},
        ),
    ]
