# Generated by Django 5.2.7 on 2026-03-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacione',
            options={'managed': True, 'permissions': [('export_pdf_cotizacione', 'Puede exportar Cotización a PDF'), ('export_excel_cotizacione', 'Puede exportar Cotización a Excel')], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallecotizaciones',
            options={'managed': True, 'permissions': [('export_pdf_detallecotizaciones', 'Puede exportar Detalle de Cotización a PDF'), ('export_excel_detallecotizaciones', 'Puede exportar Detalle de Cotización a Excel')], 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='detallerecibido',
            options={'managed': True, 'permissions': [('export_pdf_detallerecibido', 'Puede exportar Detalle Recibido a PDF'), ('export_excel_detallerecibido', 'Puede exportar Detalle Recibido a Excel')], 'verbose_name': 'Detalle Recibido', 'verbose_name_plural': 'Detalles Recibidos'},
        ),
        migrations.AlterModelOptions(
            name='estados',
            options={'managed': True, 'permissions': [('export_pdf_estados', 'Puede exportar Estado de Mueble a PDF'), ('export_excel_estados', 'Puede exportar Estado de Mueble a Excel')], 'verbose_name': 'Estado de Mueble', 'verbose_name_plural': 'Estados de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='inventariomateriale',
            options={'managed': True, 'permissions': [('export_pdf_inventariomateriale', 'Puede exportar Inventario de Material a PDF'), ('export_excel_inventariomateriale', 'Puede exportar Inventario de Material a Excel')], 'verbose_name': 'Inventario de Material', 'verbose_name_plural': 'Inventarios de Materiales'},
        ),
        migrations.AlterModelOptions(
            name='inventariomueble',
            options={'managed': True, 'permissions': [('export_pdf_inventariomueble', 'Puede exportar Inventario de Mueble a PDF'), ('export_excel_inventariomueble', 'Puede exportar Inventario de Mueble a Excel')], 'verbose_name': 'Inventario de Mueble', 'verbose_name_plural': 'Inventarios de Muebles'},
        ),
        migrations.AlterModelOptions(
            name='listacompra',
            options={'managed': True, 'permissions': [('export_pdf_listacompra', 'Puede exportar Lista de Compra a PDF'), ('export_excel_listacompra', 'Puede exportar Lista de Compra a Excel')], 'verbose_name': 'Lista de Compra', 'verbose_name_plural': 'Listas de Compras'},
        ),
        migrations.AlterModelOptions(
            name='requerimientomateriale',
            options={'managed': True, 'permissions': [('export_pdf_requerimientomateriale', 'Puede exportar Requerimiento de Material a PDF'), ('export_excel_requerimientomateriale', 'Puede exportar Requerimiento de Material a Excel')], 'verbose_name': 'Requerimiento de Material', 'verbose_name_plural': 'Requerimientos de Materiales'},
        ),
    ]
