# Generated by Django 5.2.7 on 2025-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('tipo_documento', models.CharField(db_column='Tipo_Documento')),
                ('descripcion', models.CharField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'Documentos',
                'managed': False,
            },
        ),
    ]
