# Generated by Django 5.2.7 on 2026-02-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documentos',
                'managed': True,
            },
        ),
    ]
