# Generated by Django 5.2.7 on 2026-02-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'managed': False, 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
