# Generated by Django 5.2.7 on 2025-11-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.CharField(db_column='Tipo_Documento', max_length=100)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
            ],
            options={
                'db_table': 'Documentos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
